name = "Hodgkins"
license = "MIT"
licenselink = "https://gitlab.com/whateverbits/hugo/hodgkins/-/blob/main/LICENSE"
description = "A custom grid theme for artists, including a blog and single pages for bio and contact"
homepage = "https://gitlab.com/whateverbits/hugo/hodgkins"
tags = ["grid", "portfolio"]
features = []
min_version = "0.84.4"

[author]
  name = "WhateverBits"
  homepage = "https://whateverbits.com/"

[original]
  name = "Michael Crawford"
  homepage = "https://crawford.io/"
  repo = "https://github.com/mcrwfrd/hugo-frances-theme"
