baseURL = "https://example.com/"
languageCode = "en-us"
title = "Hodgkins"
description = "Landscape and still-life painter from New Zealand."
theme = "hodgkins"

copyright = "Example"
[author]
  name = "Frances Hodgkins"
	email = "frances@example.com"
  homepage = "https://example.com/"

sectionPagesMenu = "main"
enableGitInfo = true

# Params
[params]
	# Hodgkins
	# Bootstrap CDN | false, "cdnjs", "jsdelivr", "unpkg"
	hodgBootstrapCDN = false
